#------------ MAIN OPTIONS --------------------
DEFINES  +=  -DPIC
DEFINES  +=  -DWHYDRO2
DEFINES  +=  -DWGRAV
DEFINES  +=  -DWRAD
DEFINES  +=  -DWRADHYD
DEFINES  +=  -DTESTCOSMO
DEFINES  +=  -DSTARS
#DEFINES  +=  -DSUPERNOVAE
#DEFINES  +=  -DAGN

#------------ PRECISION OPTIONS ---------------------
DEFINES  +=  -DSINGLEPRECISION

#------------ MPI OPTIONS ---------------------
DEFINES  +=  -DWMPI

#------------ CUDA OPTIONS ---------------------
DEFINES  +=  -DWCUDA_ERR

#------------ ICs OPTIONS ---------------------
DEFINES  +=  -DGRAFIC
#DEFINES  +=  -DSPLIT ### an option of GRAFIC
DEFINES  +=  -DEMMAZELDO
#DEFINES  +=  -DBULKFLOW

#------------ PIC OPTIONS ----------------------
#DEFINES += -DPART_EGY
#DEFINES += -DPERFECT
#DEFINES += -DAMRPART
#DEFINES += -DAMR_SEMILAGRANGIAN

#------------ GRAV OPTIONS ----------------------
DEFINES  += -DONFLYRED

# ----------- HYDRODYNAMICS OPTIONS ------------
DEFINES  +=  -DRIEMANN_HLLC
DEFINES  +=  -DPRIMITIVE
DEFINES  +=  -DDUAL_E
#DEFINES  +=  -DNOADX a voir 

# ----------- RADIATION OPTIONS ------------
# ici je garde une bonne partie pour le moment

DEFINES  += -DWCHEM
#DEFINES  += -DHESIMPLE
#DEFINES  += -DS_50000
#DEFINES  += -DSTARBURST_3MYR_TH
DEFINES  += -DCOOLING
DEFINES  += -DS_X
#DEFINES  += -DNORECSOURCE
#DEFINES  += -DPOLYTROP
#DEFINES  += -DJEANSCRIT
#DEFINES  += -DUVBKG
DEFINES  += -DSEMI_IMPLICIT
#DEFINES  += -DOLDCHEMRAD
DEFINES  += -DACCEL_RAD_STAR
DEFINES  += -DOTSA
#DEFINES  += -DHOMOSOURCE
#DEFINES  += -DRADSTEP
DEFINES  += -DCOARSERAD
#DEFINES  += -DSCHAYE
#DEFINES  += -DDECREASE_EMMISIVITY_AFTER_TLIFE
#DEFINES  += -DSTARS_TO_UVBKG
#DEFINES  += -DSIMPLESTAR
#DEFINES  += -DTEMPCRIT
#DEFINES  += -DMULTIPLESTARS
#DEFINES  += -DCONTINUOUSSTARS

# ---- BOUNDARY CONDITIONS (PERIODIC BY DEFAULT)--

# ---- OUTPUT--------------
#DEFINES += -DWDBG
#DEFINES += -DMOVIE
DEFINES += -DBKP
DEFINES += -DHDF5
DEFINES += -DMULTIFOLDER
DEFINES += -DALLOCT
#DEFINES += -DMPIIO
#DEFINES += -DCURIE

#DEFINES  +=  -DFULLCHECK
